/**
 * Legal policy content.
 *
 * IMPORTANT: This is a solid starting draft, not a substitute for review by
 * a licensed attorney in your jurisdiction. Placeholders in [square
 * brackets] need real values before this goes live — see LAST_UPDATED and
 * the placeholders below in particular. Keep this in sync with
 * server/legal.ts's TERMS_VERSION by hand.
 */

export const LAST_UPDATED = 'September 21, 2026';
export const TERMS_VERSION = '2026-09-21';

// Fill in the remaining bracketed placeholders before launch — the ones
// below are set from the Ospreyn PRD (South Africa is the initial market),
// but still confirm the exact registered entity name/type with whoever
// handles incorporation, since "Ospreyn" alone may be a trading name.
export const COMPANY_LEGAL_NAME = 'Ospreyn [confirm exact registered entity name, e.g. "Ospreyn (Pty) Ltd"]';
export const GOVERNING_LAW = 'the Republic of South Africa';
export const CONTACT_EMAIL = '[legal@your-ospreyn-domain.com]';
export const PRIVACY_EMAIL = '[privacy@your-ospreyn-domain.com]';
export const DMCA_AGENT_NAME = '[Designated DMCA/ECTA Agent Name]';
export const DMCA_AGENT_ADDRESS = '[Designated Agent mailing address]';
export const DMCA_AGENT_EMAIL = '[dmca@your-ospreyn-domain.com]';

export interface LegalSection {
  heading: string;
  body: string[]; // paragraphs; an item starting with "- " renders as a bullet
}

export interface LegalDocument {
  slug: string;
  title: string;
  intro?: string;
  sections: LegalSection[];
}

const NOT_LEGAL_ADVICE_NOTE =
  'Ospreyn is software that helps you record and document who owns what share of a song. ' +
  'It is not a law firm, does not provide legal advice, and using it does not create an ' +
  'attorney-client relationship. Nothing on this platform is a substitute for advice from a ' +
  'qualified lawyer familiar with your situation and jurisdiction.';

export const LEGAL_DOCS: Record<string, LegalDocument> = {
  terms: {
    slug: 'terms',
    title: 'Terms of Service',
    intro:
      'These Terms of Service ("Terms") govern your access to and use of Ospreyn (the ' +
      '"Service"), operated by ' + COMPANY_LEGAL_NAME + ' ("Ospreyn", "we", "us"). By creating an ' +
      'account or otherwise using the Service, you agree to these Terms. If you do not agree, do ' +
      'not use the Service.',
    sections: [
      {
        heading: '1. Not legal advice',
        body: [
          NOT_LEGAL_ADVICE_NOTE,
          'Rights records, split sheets and agreements generated by the Service are structured ' +
            'documentation tools based on information you and your contributors enter. We do not ' +
            'verify the accuracy of that information, do not confirm anyone\'s legal authority to ' +
            'make the claims they make, and do not guarantee that any record, confirmation or ' +
            'exported document is legally binding or enforceable in any jurisdiction. If splits, ' +
            'ownership or royalties matter to your business, have the relevant documents reviewed ' +
            'by a qualified entertainment lawyer.',
        ],
      },
      {
        heading: '2. Eligibility and accounts',
        body: [
          'You must be at least 18 years old, or the age of legal majority in your jurisdiction, ' +
            'and able to form a binding contract to use the Service.',
          'You are responsible for maintaining the confidentiality of your account credentials and ' +
            'for all activity that occurs under your account. Notify us immediately at ' +
            CONTACT_EMAIL + ' if you suspect unauthorized access.',
          'You must provide accurate registration information and keep it up to date.',
        ],
      },
      {
        heading: '3. Your content',
        body: [
          'You retain all ownership rights in the song information, contributor details, ' +
            'documents and other content you submit to the Service ("Your Content"). We do not ' +
            'claim ownership over it.',
          'By submitting Your Content, you grant us a limited, worldwide, non-exclusive license to ' +
            'host, store, process, reproduce and display it solely to operate, maintain and provide ' +
            'the Service to you and the collaborators you invite.',
          'You represent that you have the right to submit Your Content, and that doing so does not ' +
            'infringe or misappropriate any third party\'s rights, including copyright and ' +
            'publicity rights.',
          '- You are solely responsible for the accuracy of ownership percentages, contributor ' +
            'details and any claims you record.',
          '- You are solely responsible for obtaining any consent needed to add another person as a ' +
            'contributor or to submit their contact details to us for the purpose of inviting them ' +
            'to confirm a split.',
        ],
      },
      {
        heading: '4. Acceptable use',
        body: [
          'You agree not to misuse the Service. See our Acceptable Use Policy for the specifics — ' +
            'it is part of these Terms.',
        ],
      },
      {
        heading: '5. Contributor confirmations',
        body: [
          'The Service lets you invite contributors to review and electronically confirm their ' +
            'share of a song, or request a change. A confirmation recorded through the Service is ' +
            'an electronic acknowledgment, timestamped and logged with the confirming party\'s IP ' +
            'address and the text they agreed to — it is not a handwritten or notarized signature, ' +
            'and its legal weight (for example under the U.S. ESIGN Act, eIDAS in the EU, or ' +
            'equivalent local law) depends on the facts and your jurisdiction. We make no ' +
            'representation about the enforceability of any confirmation obtained through the ' +
            'Service.',
        ],
      },
      {
        heading: '6. Fees',
        body: [
          '[Describe your pricing here — e.g. "The Service is currently offered free of charge. We ' +
            'may introduce paid plans in the future, with advance notice and an opportunity to ' +
            'export your data before any change takes effect."]',
        ],
      },
      {
        heading: '7. Suspension and termination',
        body: [
          'You may stop using the Service at any time and permanently delete your account from ' +
            'your account settings. See our Privacy Policy for what deletion does and does not ' +
            'remove.',
          'We may suspend or terminate your access if you violate these Terms or the Acceptable Use ' +
            'Policy, where we reasonably believe it necessary to protect the Service, other users, ' +
            'or third parties, or as required by law. Where practical, we will give notice first.',
        ],
      },
      {
        heading: '8. Disclaimers',
        body: [
          'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, ' +
            'EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, ' +
            'FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT THE SERVICE WILL BE ' +
            'UNINTERRUPTED, ERROR-FREE OR SECURE.',
          'We do not warrant the accuracy, completeness or reliability of any content submitted by ' +
            'you or other users, including ownership claims, splits or confirmations.',
        ],
      },
      {
        heading: '9. Limitation of liability',
        body: [
          'TO THE MAXIMUM EXTENT PERMITTED BY LAW, OSPREYN AND ITS OFFICERS, EMPLOYEES AND AGENTS ' +
            'WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE ' +
            'DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA OR GOODWILL, ARISING FROM OR RELATED TO ' +
            'YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.',
          'OUR TOTAL LIABILITY FOR ANY CLAIM ARISING FROM THESE TERMS OR THE SERVICE WILL NOT ' +
            'EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM ' +
            'AROSE, OR (B) [ONE HUNDRED U.S. DOLLARS ($100)].',
          'Some jurisdictions do not allow the exclusion or limitation of certain damages, so some ' +
            'of the above limitations may not apply to you.',
        ],
      },
      {
        heading: '10. Indemnification',
        body: [
          'You agree to indemnify and hold Ospreyn harmless from any claims, damages, liabilities ' +
            'and expenses (including reasonable legal fees) arising from Your Content, your use of ' +
            'the Service in violation of these Terms, or your violation of any third party\'s ' +
            'rights.',
        ],
      },
      {
        heading: '11. Governing law and disputes',
        body: [
          'These Terms are governed by the laws of ' +
            GOVERNING_LAW +
            '. [Add your chosen dispute-resolution mechanism here — e.g. exclusive jurisdiction of ' +
            'a named South African court, or arbitration under the Arbitration Foundation of ' +
            'Southern Africa (AFSA) rules. This choice has real consequences and should be made ' +
            'with a lawyer, not left as boilerplate. If you have or expect users outside South ' +
            'Africa, consider whether you need a separate clause addressing that.]',
        ],
      },
      {
        heading: '12. Changes to these Terms',
        body: [
          'We may update these Terms from time to time. Material changes will be flagged in the ' +
            'app and, where required by law, you will be asked to accept the updated Terms before ' +
            'continuing to use the Service. The "Last updated" date above shows when the Terms ' +
            'currently in effect took effect.',
        ],
      },
      {
        heading: '13. Contact',
        body: ['Questions about these Terms: ' + CONTACT_EMAIL + '.'],
      },
    ],
  },

  privacy: {
    slug: 'privacy',
    title: 'Privacy Policy',
    intro:
      'This Privacy Policy explains what personal data Ospreyn collects, how we use it, and the ' +
      'choices you have. It applies to everyone who uses the Service, including contributors who ' +
      'access a rights record through a review link without creating an account.',
    sections: [
      {
        heading: '1. What we collect',
        body: [
          '- Account data: name, professional/stage name, email address, and a securely hashed ' +
            'password (we never store your password in readable form).',
          '- Workspace data you enter: song details, contributor names, emails and phone numbers, ' +
            'ownership splits, notes, and any documents you upload to the document vault.',
          '- Confirmation data: when a contributor confirms a split or requests a change, we record ' +
            'the action, a timestamp, their IP address and browser user agent, as evidence of what ' +
            'was agreed to.',
          '- Technical data: log data such as IP address, browser type and access times, collected ' +
            'automatically for security and troubleshooting.',
          '- Cookies: see our Cookie Policy for detail. We currently use only a strictly necessary ' +
            'session cookie to keep you signed in.',
        ],
      },
      {
        heading: '2. How we use it',
        body: [
          '- To provide the Service: create and secure your account, store and display your ' +
            'workspace data, send review invitations, and generate exports.',
          '- To communicate with you: invitation emails, confirmation and change-request ' +
            'notifications, and service-related notices (for example, about changes to these ' +
            'policies).',
          '- To keep the Service secure and working: detect abuse, debug problems, and enforce our ' +
            'Terms and Acceptable Use Policy.',
          '- To comply with legal obligations.',
          'We do not sell your personal data, and we do not use it to serve you third-party ' +
            'advertising.',
        ],
      },
      {
        heading: '3. Who we share it with',
        body: [
          'We share data only with the service providers that make Ospreyn work, under contracts ' +
            'that limit their use of it to providing that service to us:',
          '- Database and application hosting.',
          '- Object storage for uploaded documents (or local disk storage on this deployment when ' +
            'object storage is not configured — see the Document Vault section below).',
          '- Transactional email delivery (Resend, SendGrid or Postmark, depending on how this ' +
            'deployment is configured), used only to send the invitation and notification emails ' +
            'described above.',
          'We may also disclose data where required by law, to protect our rights or the safety of ' +
            'others, or in connection with a merger, acquisition or sale of assets (with notice to ' +
            'you where required by law).',
          'Contributors: a contributor\'s name, email/phone and the split you propose for them are ' +
            'visible to the workspace owner who added them and to anyone else with access to that ' +
            'workspace. We send the contributor an email with a private review link so they can see ' +
            'and confirm their own information.',
        ],
      },
      {
        heading: '4. Document vault and storage mode',
        body: [
          'Documents you upload are stored in private object storage, accessed only through ' +
            'short-lived, signed URLs. If this deployment has not configured a dedicated object ' +
            'storage provider, it falls back to storing files on the server\'s local disk, secured ' +
            'the same way (signed, time-limited URLs) but without the same durability guarantees. ' +
            'Ask your workspace administrator which mode is active if this matters to you — the ' +
            'app reports it under Settings.',
        ],
      },
      {
        heading: '5. Data retention',
        body: [
          'We retain your data for as long as your account is active, plus a reasonable period ' +
            'afterward for legal, security and record-keeping purposes as described below.',
        ],
      },
      {
        heading: '6. Deleting your account',
        body: [
          'You can permanently delete your account from Account Settings at any time. When you do:',
          '- We revoke your active sessions immediately and disable sign-in.',
          '- We replace your name, email and password with anonymized values, so your account can ' +
            'no longer identify you.',
          '- If you are the sole member of a workspace, we delete that workspace and everything in ' +
            'it — songs, splits, invitations, confirmations, agreements, audit history and uploaded ' +
            'documents — permanently.',
          '- If your workspace has other members, you\'ll need to remove them or transfer ownership ' +
            'first (contact ' +
            CONTACT_EMAIL +
            ' for help), so their access and records are not silently destroyed.',
          'We keep the minimum needed to preserve other people\'s legitimate records: for example, ' +
            'if you invited a contributor and they confirmed a split in someone else\'s workspace, ' +
            'that confirmation and the fact that you sent the invitation remain part of that ' +
            'workspace\'s audit trail — your account is anonymized rather than the historical event ' +
            'being erased, so the workspace owner keeps an accurate record. This mirrors the ' +
            '"erasure of personal data, retention of the minimum needed for legitimate ' +
            'record-keeping" approach recognized by GDPR Article 17(3) and comparable laws ' +
            'elsewhere.',
        ],
      },
      {
        heading: '7. Your rights',
        body: [
          'Ospreyn\'s initial market is South Africa, and personal information is processed in ' +
            'accordance with the Protection of Personal Information Act, 2013 ("POPIA"). Under ' +
            'POPIA you have the right to request access to, correction of, or deletion of your ' +
            'personal information, to object to its processing, and to complain to the Information ' +
            'Regulator (South Africa) if you believe we have handled it unlawfully.',
          'Depending on where else you use the Service, you may have similar rights under other ' +
            'laws — for example the right to access, correct, delete, export, or restrict our use ' +
            'of your personal data, and to object to certain processing, under the GDPR (EEA/UK) or ' +
            'the CCPA/CPRA (California). Most of this you can do directly in the app (editing your ' +
            'details, exporting an evidence package, deleting your account). For anything else, ' +
            'contact ' +
            PRIVACY_EMAIL +
            '. We will respond within the time required by applicable law.',
          'We do not sell or share personal information as those terms are defined by the CCPA.',
        ],
      },
      {
        heading: '8. International transfers',
        body: [
          '[Describe where your servers and providers are located. If personal information leaves ' +
            'South Africa, POPIA section 72 requires that the recipient country have adequate ' +
            'data-protection law, or that another safeguard apply (e.g. the individual\'s consent, ' +
            'or a contract that enforces POPIA-equivalent protections). If you also have EEA/UK ' +
            'users, state what transfer mechanism you rely on for transfers outside those regions — ' +
            'for example Standard Contractual Clauses.]',
        ],
      },
      {
        heading: "9. Children's privacy",
        body: [
          'The Service is not directed at, and we do not knowingly collect personal data from, ' +
            'anyone under 18 (or the age of majority in their jurisdiction). If you believe a child ' +
            'has provided us with personal data, contact ' +
            PRIVACY_EMAIL +
            ' and we will delete it.',
        ],
      },
      {
        heading: '10. Security',
        body: [
          'We use industry-standard measures to protect your data, including encryption in transit, ' +
            'hashed passwords, and access controls scoped to your workspace. No method of ' +
            'transmission or storage is 100% secure, and we cannot guarantee absolute security.',
        ],
      },
      {
        heading: '11. Changes to this policy',
        body: [
          'We may update this Privacy Policy from time to time. Material changes will be flagged in ' +
            'the app. The "Last updated" date above shows when the version currently in effect took ' +
            'effect.',
        ],
      },
      {
        heading: '12. Contact',
        body: ['Questions about this policy or your data: ' + PRIVACY_EMAIL + '.'],
      },
    ],
  },

  cookies: {
    slug: 'cookies',
    title: 'Cookie Policy',
    intro:
      'This policy explains how Ospreyn uses cookies and similar technologies, and applies ' +
      'alongside our Privacy Policy.',
    sections: [
      {
        heading: 'What we currently use',
        body: [
          'Ospreyn currently uses exactly one cookie: a strictly necessary session cookie that ' +
            'keeps you signed in and identifies your session to our API. It is essential to the ' +
            'Service working and cannot be switched off — without it, you would be signed out on ' +
            'every page load.',
          'We do not currently use analytics, advertising, or third-party tracking cookies.',
        ],
      },
      {
        heading: 'If that changes',
        body: [
          'If we ever add analytics or other non-essential cookies, we will update this policy and, ' +
            'where required by law, ask for your consent before setting them.',
        ],
      },
      {
        heading: 'Managing cookies',
        body: [
          'Because our only cookie is strictly necessary, there is no in-app toggle to disable it — ' +
            'disabling it would sign you out. You can clear or block cookies through your browser ' +
            'settings at any time; doing so for Ospreyn will sign you out and require you to sign ' +
            'back in.',
        ],
      },
    ],
  },

  'acceptable-use': {
    slug: 'acceptable-use',
    title: 'Acceptable Use Policy',
    intro:
      'This Acceptable Use Policy is part of our Terms of Service and applies to everyone who ' +
      'uses the Service.',
    sections: [
      {
        heading: 'You agree not to',
        body: [
          '- Submit false, fraudulent or knowingly inaccurate ownership, split or contributor ' +
            'information, or misrepresent your authority to make a claim over a song.',
          '- Use the Service to infringe or misappropriate anyone\'s copyright, trademark, ' +
            'publicity, privacy or other legal rights.',
          '- Upload malware, or attempt to gain unauthorized access to any account, workspace, or ' +
            'part of the Service or its infrastructure.',
          '- Scrape, harvest or bulk-extract data from the Service other than through the exports we ' +
            'provide for your own workspace.',
          '- Use the invitation system to send unsolicited communications to people who are not ' +
            'genuine contributors to a song, or otherwise abuse it as a spam vector.',
          '- Impersonate any person or entity, or misrepresent your affiliation with any person or ' +
            'entity.',
          '- Reverse engineer, decompile, or attempt to extract the source code of the Service, ' +
            'except where applicable law gives you the right to do so despite this restriction.',
          '- Use the Service in any way that violates applicable law, or that could damage, disable, ' +
            'overburden or impair it.',
          '- Upload content you do not have the right to upload, including copyrighted recordings, ' +
            'compositions or documents you do not own and are not authorized to store or share.',
        ],
      },
      {
        heading: 'Enforcement',
        body: [
          'We may investigate suspected violations and take action we consider appropriate, ' +
            'including removing content, suspending or terminating accounts, and reporting conduct ' +
            'to law enforcement where warranted.',
        ],
      },
      {
        heading: 'Reporting a violation',
        body: ['Report suspected violations to ' + CONTACT_EMAIL + '.'],
      },
    ],
  },

  copyright: {
    slug: 'copyright',
    title: 'Copyright & DMCA Policy',
    intro:
      'Ospreyn respects intellectual property rights and expects users of the Service to do the ' +
      'same. This policy explains how to report claimed copyright infringement. It follows the ' +
      'notice-and-takedown structure used under the U.S. Digital Millennium Copyright Act ' +
      '("DMCA"), which we use as our procedure regardless of jurisdiction since it is the ' +
      'internationally recognized model. If you are in South Africa, section 77 of the Electronic ' +
      'Communications and Transactions Act, 2002 ("ECTA") provides an equivalent notice ' +
      'procedure and limitation of liability for service providers who act on valid notices — the ' +
      'same notice below is intended to satisfy both. [Confirm the ECTA-specific requirements, ' +
      'including registration with an approved industry representative body, with South African ' +
      'counsel.]',
    sections: [
      {
        heading: 'Filing a notice of claimed infringement',
        body: [
          'If you believe content stored on or accessible through the Service infringes your ' +
            'copyright, send a written notice to our designated agent that includes:',
          '- A physical or electronic signature of the copyright owner or someone authorized to act ' +
            'on their behalf.',
          '- Identification of the copyrighted work claimed to have been infringed.',
          '- Identification of the material claimed to be infringing, and information reasonably ' +
            'sufficient to let us locate it (for example, a link or the workspace/song name).',
          '- Your contact information: address, telephone number and email address.',
          '- A statement that you have a good faith belief that the use is not authorized by the ' +
            'copyright owner, its agent, or the law.',
          '- A statement, made under penalty of perjury, that the information in the notice is ' +
            'accurate and that you are the copyright owner or authorized to act on their behalf.',
        ],
      },
      {
        heading: 'Designated agent',
        body: [
          DMCA_AGENT_NAME + '\n' + DMCA_AGENT_ADDRESS + '\nEmail: ' + DMCA_AGENT_EMAIL,
        ],
      },
      {
        heading: 'Counter-notification',
        body: [
          'If you believe material you posted was removed or disabled by mistake or ' +
            'misidentification, you may send a counter-notice to our designated agent containing:',
          '- Your physical or electronic signature.',
          '- Identification of the material removed and its location before removal.',
          '- A statement, under penalty of perjury, that you have a good faith belief the material ' +
            'was removed or disabled as a result of mistake or misidentification.',
          '- Your name, address and telephone number, and a statement that you consent to the ' +
            'jurisdiction of the federal court in your district (or, if outside the U.S., an ' +
            'appropriate jurisdiction) and will accept service of process from the person who filed ' +
            'the original notice.',
          'Upon receiving a valid counter-notice, we may restore the material within the time ' +
            'required by law unless the original complainant files a court action seeking to ' +
            'restrain the alleged infringer.',
        ],
      },
      {
        heading: 'Repeat infringers',
        body: [
          'We will, in appropriate circumstances, terminate the accounts of users who are repeat ' +
            'infringers.',
        ],
      },
    ],
  },
};

export function getLegalDoc(slug: string | undefined): LegalDocument | null {
  if (!slug) return null;
  return LEGAL_DOCS[slug] || null;
}
